name:                playground
version:             0.1.0.0
github:              "cohei/playground"
license:             BSD3
author:              "TANIGUCHI Kohei"
maintainer:          "a.d.xvii.kal.mai@gmail.com"
copyright:           "2018 TANIGUCHI Kohei"

extra-source-files:
  - README.md
  - package.yaml

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cohei/playground/tree/master/haskell#playground>

dependencies:
  - base >= 4.7 && < 5
  - adjunctions
  - array
  - containers
  - data-memocombinators
  - distributive
  - filepath
  - MonadRandom
  - mtl
  - path
  - path-io
  - profunctors
  - refined
  - Stream
  - time
  - transformers
  - utility

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wmissing-local-signatures
  - -Wmonomorphism-restriction
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fdefer-typed-holes

library:
  source-dirs: src

executables:
  zundoko:
    main: Main.hs
    source-dirs: app/zundoko
  janken:
    main: Main.hs
    source-dirs: app/janken
  flattenDirectory:
    main: Main.hs
    source-dirs: app/flattenDirectory

tests:
  playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - playground
      - hspec
      - IOSpec
      - QuickCheck
  doctest:
    main: Main.hs
    source-dirs: test/doctest
    dependencies:
      - doctest

build-type: Custom
custom-setup:
  dependencies:
    - base
    - Cabal
    - hpack
