name:                playground
version:             0.1.0.0
github:              "cohei/playground"
license:             BSD3
author:              "TANIGUCHI Kohei"
maintainer:          "a.d.xvii.kal.mai@gmail.com"
copyright:           "2018 TANIGUCHI Kohei"

extra-source-files:
  - README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cohei/playground/tree/master/haskell#playground>

dependencies:
  - base >= 4.7 && < 5
  - array
  - MonadRandom
  - mtl
  - profunctors
  - refined
  - transformers
  - utility

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-import-lists
  - -Wredundant-constraints
  - -fdefer-typed-holes

library:
  source-dirs: src

executables:
  zundoko:
    main: Main.hs
    source-dirs: app/zundoko
  janken:
    main: Main.hs
    source-dirs: app/janken

tests:
  playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - playground
      - hspec
      - IOSpec
      - QuickCheck
